package main

import "fmt"

func main() {
	codigoMsg := map[int]string{
		0:    "Transação autorizada",
		1000: "Transação não autorizada",
		1001: "Cartão vencido",
		1002: "Transação não permitida",
		1003: "Rejeitado emissor",
		1004: "Cartão com restrição",
		1005: "Transação não autorizada",
		1006: "Tentativas de senha excedidas",
		1007: "Rejeitado emissor",
		1008: "Rejeitado emissor",
		1009: "Transação não autorizada",
		1010: "Valor inválido",
		1011: "Cartão inválido",
		1013: "Transação não autorizada",
		1014: "Tipo de conta inválido",
		1015: "Função não suportada",
		1016: "Saldo insuficiente",
		1017: "Senha inválida",
		1019: "Transação não permitida",
		1020: "Transação não permitida",
		1021: "Rejeitado emissor",
		1022: "Cartão com restrição",
		1023: "Rejeitado emissor",
		1024: "Transação não permitida",
		1025: "Cartão bloqueado",
		1027: "Excedida a quantidade de transações para o cartão",
		1042: "Tipo de conta inválido",
		1045: "Código de segurança inválido",
		1049: "Banco/emissor do cartão inválido",
		2000: "Cartão com restrição",
		2001: "Cartão vencido",
		2002: "Transação não permitida",
		2003: "Rejeitado emissor",
		2004: "Cartão com restrição",
		2005: "Transação não autorizada",
		2006: "Tentativas de senha excedidas",
		2007: "Cartão com restrição",
		2008: "Cartão com restrição",
		2009: "Cartão com restrição",
		5003: "Erro interno",
		5006: "Erro interno",
		5025: "Código de segurança (CVV) do cartão não foi enviado",
		5054: "Erro interno",
		5062: "Transação não permitida para este produto ou serviço",
		5086: "Cartão poupança inválido",
		5088: "Transação não autorizada Amex",
		5089: "Erro interno",
		5092: "O valor solicitado para captura não é válido ",
		5093: "Banco emissor Visa indisponível",
		5095: "Erro interno",
		5097: "Erro interno",
		9102: "Transação inválida",
		9103: "Cartão cancelado",
		9107: "O banco/emissor do cartão ou a conexão parece estar offline",
		9108: "Erro no processamento",
		9109: "Erro no processamento",
		9111: "Time-out na transação",
		9112: "Emissor indisponível",
		9113: "Transmissão duplicada",
		9124: "Código de segurança inválido",
		9999: "Erro não especificado",
	}

	for k, v := range codigoMsg {
		fmt.Println(k, v)
	}

	codigoOrientacao := map[int]string{
		1000: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1001: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1002: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1003: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1004: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1005: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1006: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1007: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1008: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1009: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1010: "É possível que o tipo de operação seja inválido. Ex.: cartão de débito onde se aceita apenas crédito ",
		1011: "O número do cartão digitado está incorreta. Oriente o portador a tentar novamente, se atentando ao preenchimento do número do cartão",
		1013: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1014: "O tipo de conta selecionado não existe",
		1015: "É possível que o tipo de operação seja inválido. Ex.: cartão de débito onde se aceita apenas crédito",
		1016: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1017: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1019: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1020: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1021: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1022: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1023: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1024: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1025: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1027: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		1042: "O tipo de conta selecionado não existe",
		1045: "O CVV digitado está incorreto. Oriente o portador a tentar novamente, se atentando ao preenchimento do CVV",
		1049: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		2000: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		2001: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		2002: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		2003: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		2004: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		2005: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		2006: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		2007: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		2008: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		2009: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		5003: "Retente a transação",
		5006: "Retente a transação",
		5025: "Certifique-se que foi realizado o envio do CVV no fechamento do checkout",
		5054: "Retente a transação",
		5062: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		5086: "O tipo de conta selecionado não existe",
		5088: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		5089: "Retente a transação",
		5092: "Transação não autorizada",
		5095: "Retente a transação",
		5097: "Retente a transação",
		9102: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		9103: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		9107: "Oriente o portador a entrar em contato com o banco emissor do cartão.",
		9108: "Retente a transação",
		9109: "Retente a transação",
		9111: "Retente a transação",
		9112: "Oriente o portador a entrar em contato com o banco emissor do cartão",
		9113: "É possível que o cliente já tenha realizado a compra com sucesso e está erroneamente enviando o pagamento uma segunda vez",
		9124: "O CVV digitado está incorreto. Oriente o portador a tentar novamente, se atentando ao preenchimento do CVV",
		9999: "Retente a transação",
	}
	for k, v := range codigoOrientacao {
		fmt.Println(k, v)
	}

}
